# Generated by Django 5.2.1 on 2025-05-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Archivo')),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
